# Generated by Django 5.0.4 on 2024-05-11 02:53

import datetime
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="blog/images/")),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("date", models.DateField(default=datetime.date.today)),
                ("content", models.TextField()),
            ],
        ),
    ]


