# Generated by Django 5.0.4 on 2024-05-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_rating_alter_post_author_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
